#!/bin/sh

trap exit ERR

DIR=x264-i386

git clone git://git.videolan.org/x264.git $DIR

cd $DIR
mkdir -p dist

CC=/Developer2/Platforms/iPhoneSimulator.platform/Developer/usr/bin/i686-apple-darwin10-gcc-4.2.1 ./configure --sysroot=/Developer2/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator4.1.sdk --prefix='dist' 

make && make install

echo "Installed: $DIR/dist"


