#!/bin/sh

trap exit ERR

DIR=x264-armv6

git clone git://git.videolan.org/x264.git $DIR

cd $DIR
mkdir -p dist

CC=/Developer2/Platforms/iPhoneOS.platform/Developer/usr/bin/gcc-4.2 ./configure --host=arm-apple-darwin --sysroot=/Developer2/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS4.1.sdk --prefix='dist' --extra-cflags='-arch armv6' --extra-ldflags='-arch armv6' --enable-pic --disable-asm

make && make install

echo "Installed: $DIR/dist"
